# Generated by Django 4.2.3 on 2023-07-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0009_alter_joke_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joke',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='jokes', to='jokes.tag'),
        ),
    ]
