# Generated by Django 4.2.3 on 2023-07-23 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0012_jokevote_jokevote_one_vote_per_user_per_joke'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={},
        ),
    ]
